catalog/urls.py
from django.urls import path
from . import views

app_name = 'catalog'

urlpatterns = [
    path('', views.index, name='index'),
    path('book/', views.book, name='book'),
    path('book/<int:pk>', views.book_detail, name='book_detail'),
    path('author/', views.author, name='author'),
    path('author/<int:pk>', views.author_detail, name='author_detail'),
    path('accounts/login', views.login, name='login'),
    path('accounts/logout', views.logout, name='logout'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('borrowed/', views.LoanedBooksByLibrarianListView.as_view(),
         name='borrowed'),
    path('form/', views.form, name='form'),
    path('form/<str:name>', views.form_detail, name='form_detail'),    
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('catalog.urls')),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date

import uuid  # Required for unique book instances


# Create your models here.

class Genre(models.Model):
    """Model representing a book genre."""
    name = models.CharField(
        max_length=200, help_text='Enter a book genre (e.g. Science Fiction)')

    def __str__(self):
        """String for representing the Model object."""
        return self.name


class Language(models.Model):
    """Model representing a book language."""
    name = models.CharField(
        max_length=200, help_text='Enter a book language (e.g. Science Fiction)')

    def __str__(self):
        """String for representing the Model object."""
        return self.name


class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)

    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author is a string rather than an object because it hasn't been declared yet in the file
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)

    summary = models.TextField(
        max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13, unique=True,
                            help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')

    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    genre = models.ManyToManyField(
        Genre, help_text='Select a genre for this book')

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        """Returns the URL to access a detail record for this book."""
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'


class BookInstance(models.Model):

    class Meta:
        # …
        permissions = (("can_mark_returned", "Set book as returned"),)

    borrower = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)

    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    def is_overdue(self):
        return bool(self.due_back and date.today() > self.due_back)

    class Meta:
        ordering = ['due_back']

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'


class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the URL to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'

catalog/forms.py
import datetime

from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _


class RenewBookForm(forms.Form):
    renewal_date = forms.DateTimeField(
        help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(
                _('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data

catalog/views.py
import datetime
from django.shortcuts import render, get_object_or_404
from .models import Book, Author, Genre, BookInstance
from django.views import generic
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse
from catalog.forms import RenewBookForm


# Create your views here.


def index(request):

    # Generate counts of some of the main objects
    num_of_books = Book.objects.all().count
    num_of_instances = BookInstance.objects.all().count
    num_of_genres = Genre.objects.filter(name__exact='Fantasy').count

    # Available books (status = 'a')
    num_of_instances_available = BookInstance.objects.filter(
        status__exact='a').count

    # The 'all()' is implied by default.
    num_of_authors = Author.objects.count

    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_of_books': num_of_books,
        'num_of_instances': num_of_instances,
        'num_of_instances_available': num_of_instances_available,
        'num_of_authors': num_of_authors,
        'num_visits': num_visits,
        'num_of_genres' : num_of_genres
    }

    return render(request, 'catalog/index.html', context)


@login_required
def book(request):
    paginate_by = 2
    books = Book.objects.all().values()
    return render(request, 'catalog/book.html', {'books': books})


@login_required
def author(request):
    authors = Author.objects.all().values()
    return render(request, 'catalog/author.html', {'authors': authors})


class BookListView(generic.ListView):
    model = Book

    # your own name for the list as a template variable
    context_object_name = 'book_list'
    queryset = Book.objects.filter(title__icontains='war')[
        :5]  # Get 5 books containing the title war
    # Specify your own template name/location
    template_name = 'templates/book_list.html'


'''
    def get_queryset(self):
        return Book.objects.filter(title__icontains='war')[:5] # Get 5 books containing the title war
    
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(BookListView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        context['some_data'] = 'This is just some data'
        return context
'''


class AuthorListView(generic.ListView):
    model = Author


def book_detail(request, pk):
    book = Book.objects.get(pk=pk)
    return render(request, 'catalog/book_detail.html', {'book': book, })


def author_detail(request, pk):
    author_details = Author.objects.get(pk=pk)
    return render(request, 'catalog/author_detail.html', {'author_details': author_details})


def login(request):
    return render(request, 'registration/login.html')


def logout(request):
    return render(request, 'registration/logout.html')


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """Generic class-based view listing books on loan to current user."""
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return (
            BookInstance.objects.filter(borrower=self.request.user)
            .filter(status__exact='o')
            .order_by('due_back')
        )


class LoanedBooksByLibrarianListView(generic.ListView):
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_librarian.html'
    paginate_by = 10

    def get_queryset(self):
        return (
            BookInstance.objects.filter(borrower=self.request.user)
            .filter(status__exact='o')
            .order_by('due_back')
        )


def form(request):
    return render(request, 'catalog/test_form.html')


def form_detail(request, name):
    idx = name
    return render(request, 'catalog/test_form_detail.html', {'idx': idx})

@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def renew_book_librarian(request, pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = RenewBookForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('all-borrowed'))

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'book_instance': book_instance,
    }

    return render(request, 'catalog/book_renew_librarian.html', context)

catalog/templates/catalog/author.html
{% extends 'catalog/base.html' %}
{% block content %}
  <h1>Local Library Author</h1>
  <p>
    Welcome to LocalLibrary, a website developed by
    <em>Mozilla Developer Network</em>!
  </p>
  <h2>Dynamic content</h2>
  <p>The library has the following authors:</p>
  
    {% if authors %}
    <ul>
        {% for author in authors %}
        <li><strong>Author {{ author.id }} :</strong> <a href = "{% url 'catalog:author_detail' author.id %}">{{ author.first_name }}, {{author.last_name }}</a></li>
        <div>
            below
            {{author.book_set.all}}
        </div>
        {% endfor %}
    </ul>
    {% else %}
        <h1>There are no authors available</h1>     
    {% endif %}

{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends 'catalog/base.html' %}

{% block content %}
    {{author_details}}<br>
    <p> Born: {{author_details.date_of_birth}} </p>
    <p> Died: {{author_details.date_of_death}} </p>
{% endblock %}

catalog/templates/catalog/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block title %}
      <title>Local Library ({{user}})</title>
    {% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous" />
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    {% load static %}
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-2">
          {% block sidebar %}
            <ul class="sidebar-nav">
              <li><a href="{% url 'catalog:index' %}">Home</a></li>
              <li><a href="{% url 'catalog:book' %}">All books</a></li>
              <li><a href="{% url 'catalog:author' %}">All authors</a></li>
            </ul>

            {% if user.is_authenticated %}
            User: {{ user.get_username }}

            <ul>
            <li><a href="{% url 'catalog:my-borrowed' %}">My Borrowed</a></li>
            <li><a href="{% url 'users:logout' %}?next={{ request.path }}">Logout</a></li>
            <li><a href="{% url 'users:login' %}?next={{ request.path }}">Login</a></li>
            </ul>  
            Staff
          {% else %}
          {% endif %}
          {% endblock %}
        </div>
        <div class="col-sm-10 ">
            {% block content %}

            {% endblock %}
            {% block pagination %}
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
  {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

catalog/templates/catalog/book.html
{% extends 'catalog/base.html' %}
{% block content %}
  <h1>Local Library Book</h1>
  <p>
    Welcome to LocalLibrary, a website developed by
    <em>Mozilla Developer Network</em>!
  </p>
  <h2>Dynamic content</h2>
  <p>The library has the following books:</p>
  
    {% if books %}
    <ul>
        {% for book in books %}
        <li><strong>Book {{book.id}} :</strong> <a href="{% url 'catalog:book_detail' book.id %}">{{ book.title }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
        <h1>There are no books available</h1>     
    {% endif %}

{% endblock %}

catalog/templates/catalog/book_detail.html
{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="{% url 'catalog:author_detail' book.author.pk %}">{{ book.author }}</a></p>
  <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Language:</strong> {{ book.language }}</p>
  <p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
      <hr />
      <p
        class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
      </p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
      <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
    {% endfor %}
  </div>
  {% endblock %}

catalog/templates/catalog/book_renew_librarian.html
{% extends "catalog/base.html" %}

{% block content %}
  <h1>Renew: {{ book_instance.book.title }}</h1>
  <p>Borrower: {{ book_instance.borrower }}</p>
  <p {% if book_instance.is_overdue %} class="text-danger"{% endif %} >Due date: {{ book_instance.due_back }}</p>

  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>

  <tr>
    <th><label for="id_renewal_date">Renewal date:</label></th>
    <td>
      <ul class="errorlist">
        <li>Invalid date - renewal in past</li>
      </ul>
      <input
        id="id_renewal_date"
        name="renewal_date"
        type="text"
        value="2015-11-08"
        required />
      <br />
      <span class="helptext">
        Enter date between now and 4 weeks (default 3 weeks).
      </span>
    </td>
  </tr>
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_librarian.html
{% extends "catalog/base.html" %}

{% block content %}
    <h1>All Borrowed Books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      {% if perms.catalog.can_mark_returned %}- <a href="{% url 'catalog:renew-book-librarian' bookinst.id %}">Renew</a>{% endif %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'catalog:book_detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a> ({{ bookinst.due_back }}) - {{user.name}}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "catalog/base.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'catalog:book_detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a> ({{ bookinst.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/index.html
{% extends "catalog/base.html" %}

{% block title %}
Index Page
{% endblock title %}
{% block content %}
  <h1>Local Library Home</h1>
  <p>
    Welcome to LocalLibrary, a website developed by
    <em>Mozilla Developer Network</em>!
  </p>
  <h2>Dynamic content</h2>
  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Books:</strong> {{ num_of_books }}</li>
    <li><strong>Copies:</strong> {{ num_of_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_of_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_of_authors }}</li>
    <li><strong>Genres:</strong> {{ num_of_genres }}</li>

  </ul>
  <p>
    You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}.
  </p>
{% endblock %}

catalog/templates/catalog/test_form.html
{% extends 'catalog/base.html' %}

{% block title %}
    Test Forms
{% endblock %}

{% block content %}
    <form action="catalog/test_form_detail.html" method="post">
        {% csrf_token %}
        
        <label for="team_name">Enter name:</label>
        <input 
            id="team_name"
            type="text"
            name="name_field"
            value="Default name for team." />
        <input type="submit" value="OK"/>
    </form>
    <br>
    <form>
        <label for="">Number 1:</label>
        <input type="text"/><br><br>
        <label for="">Number 2:</label>
        <input type="text"/><br><br>
        <label for="">Sum:</label>
        <input type="text" /><br><br>
        <input type="submit" value="Sum"/>
    </form>
{% endblock %}

catalog/templates/catalog/test_form_detail.html
{% extends 'catalog/base.html' %}

{% block title %}
    Test Forms
{% endblock %}

{% block content %}
    <h1>Form detail {{idx}}</h1>
    <form action="">
        {% csrf_token %}
        <input >
    </form>
{% endblock %}